version: '3'

networks:
    app-net:
        driver: bridge

services:
  php:
    container_name: php
    build:
      context: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
        - app-net

  database:
    container_name: database
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=report
      - MYSQL_USER=report
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
        - app-net

volumes:
  db-data: ~
